### ISSUE TITLE
It is unnecessary to get comps from lolchess every time you run main.py

### ISSUE THREAD

**Issue by IssacSaMa** [Sizzzles/TFT-OCR-BOT#11]
Set an instruction after running main.py to confirm whether to update comps from lolchess.

**Comment by Sizzzles** [comment]
I'll try getting to this when I can... For now you can remove the lines 63-70 in main.py. Should start with   """checks if auto_comp files exist and deletes them""" and end with os.remove("cached_data\inputed

**Comment by IssacSaMa** [comment]
> I'll try getting to this when I can... For now you can remove the lines 63-70 in main.py. Should start with """checks if auto_comp files exist and deletes them""" and end with os.remove("cached_data\inputed

Ok, I see. Thank you.

**Comment by Sizzzles** [comment]
Should note after removing those lines of code if you want updated comps just delete delete the cached_data folder before running main.py

**Comment by Sizzzles** [comment]
@IssacSaMa I'm actually interested are you having the same issue with the original bot?

**Comment by Sizzzles** [comment]
Referenced the wrong issue in my latest commit but now you have the option if you want to update comps. If there are any issues let me know otherwise this issue can be closed. And thank you for the suggestion!

**Comment by Sizzzles** [comment]
Now have the option if you want to update comps. If there are any issues let me know otherwise this issue can be closed. And thank you for the suggestion!
