### ISSUE TITLE
bot crash

### ISSUE THREAD

**Issue by FrapzHaash** [Sizzzles/TFT-OCR-BOT#13]
![Untitled](https://user-images.githubusercontent.com/80805708/229257840-a2c1daca-ba8a-4454-9797-c96a84b0333a.png)

**Comment by Sizzzles** [comment]
Is this happening all the time? Make sure you have the latest files and let me know how it goes. I'm failing replicate this issue

**Comment by FrapzHaash** [comment]
I tried it again and this time it worked well, possibly because I have numpy:1.24.1 instead of 1.23.0 in the requirements, since I get an error if I try to install that version, sorry for the delay.
