### ISSUE TITLE
Crawl data problem

### ISSUE THREAD

**Issue by kizxlove** [Sizzzles/TFT-OCR-BOT#26]
It seems that the bot cannot crawl data from lolchest from today 16 Nov.
![image](https://github.com/Sizzzles/TFT-OCR-BOT/assets/90539493/7d5f9362-515d-4bc0-89a3-ca8f8e2eee28)

**Comment by Sizzzles** [comment]
Noted. Will look into this on the weekend when I have time

**Comment by Sizzzles** [comment]
This should be fixed now
