### ISSUE TITLE
comps not loading

### ISSUE THREAD

**Issue by Sastter** [Sizzzles/TFT-OCR-BOT#30]
![Captura de tela 2024-02-07 105918](https://github.com/Sizzzles/TFT-OCR-BOT/assets/148476045/a54274f3-96b9-47b5-b3ed-e872d0830885)

how do i fix? tried everything

**Comment by ColossalCalamari** [comment]
Same issue occurring here.

**Comment by Sizzzles** [comment]
I have to fix it.... I'll figure something out

**Comment by Sizzzles** [comment]
Should be fixed now. Didn't test but it looks right from what I can see.
If you have anymore problems let me know :)

**Comment by Sastter** [comment]
> Should be fixed now. Didn't test but it looks right from what I can see. If you have anymore problems let me know :)

thanks man, you're a legend, hope everything is going well in your life and personal projects thoo
