### ISSUE TITLE
Other Comp Websites

### ISSUE THREAD

**Issue by OGBDarko** [Sizzzles/TFT-OCR-BOT#31]
Im very new to all of this.
Is it possible to change the comps from lolchess to metatft and if it's possible how do i do it?

**Comment by Sizzzles** [comment]
Not possible and probably won't be added. Metatft has too much going on and I think it would just be a nightmare to scrape. Already have enough trouble trying to figure out what has changed with lolchess when they decide to update something in the background of the site.

I'll keep this around though and if enough interest is shown I'll look into maybeeeee adding multiple sites whenever I get some free time

**Comment by Sizzzles** [comment]
Added a Discussion for this #34
Has a poll so I can gauge interest assuming I can actually figure out code to add more sites...
