### ISSUE TITLE
Cannot run main.py file

### ISSUE THREAD

**Issue by konoha1231** [Sizzzles/TFT-OCR-BOT#32]
I have installed the application versions but cannot run the main.py file. I open the install file and what does it look like? Do you have any way to fix it?
![Capture](https://github.com/Sizzzles/TFT-OCR-BOT/assets/151894058/e683b82b-fad2-4023-b302-ebfdb8c20363)

**Comment by Sizzzles** [comment]
Pushed a fix. Just run install.py then run main.py. If you have trouble running main.py by double clicking then open cmd and change the directory `cd d: game\lol\tft\tft-ocr-bot-main` in your case then press enter then type `main.py` and press enter the bot should work for you if it doesn't try `py main.py` instead
