### ISSUE TITLE
Stuck here

### ISSUE THREAD

**Issue by element221** [Sizzzles/TFT-OCR-BOT#39]
![image](https://github.com/Sizzzles/TFT-OCR-BOT/assets/75669548/48c96fd1-ead8-4650-b363-a42950069b75)

**Comment by Sizzzles** [comment]
Will push fix soon

**Comment by Sizzzles** [comment]
@element221 should be good now. Let me know if there are any issues

**Comment by kizxlove** [comment]
> @element221 should be good now. Let me know if there are any issues

![image](https://github.com/Sizzzles/TFT-OCR-BOT/assets/90539493/e61ec98e-d118-4fb2-bb59-2b2981384b14)
there is still a bug related to Kayle, I think this might be champion database problem.

**Comment by Sizzzles** [comment]
@kizxlove have a fixed but haven't pushed yet due to testing

**Comment by Sizzzles** [comment]
Made more changes so will push fix after work if I have no crashes 😄

**Comment by kizxlove** [comment]
> Made more changes so will push fix after work if I have no crashes 😄

I have fixed it myself but still wait for your update bro xD

**Comment by Sizzzles** [comment]
@element221 @kizxlove should be all good now
