### ISSUE TITLE
Error when launching main.py

### ISSUE THREAD

**Issue by Lexorily** [Sizzzles/TFT-OCR-BOT#4]
![image](https://user-images.githubusercontent.com/79978135/219686611-5b7942ab-d41e-4b5b-b20b-75f4e1a4d9c7.png)

**Comment by Sizzzles** [comment]
Yes bot is currently broken due to [lolchess](https://lolchess.gg/?hl=en) updating their site. I'll try and fix this as soon as I can but have no eta

**Comment by Sizzzles** [comment]
Comps should be fixed now. Let me know if you are still having problems :)

**Comment by diivien** [comment]
Hi, no comps are showing or loaded. 
![image](https://user-images.githubusercontent.com/100516930/221489408-fd9a6790-950e-4d4c-b769-079caf76b0e0.png)

**Comment by Sizzzles** [comment]
Okay guess it loves breaking after I fix. I'll look into it. I'm getting the same thing

**Comment by huy4vn** [comment]
Hi @Sizzzles i think we should use their API. i found an API here to get the comps : https://tft.dakgg.io/api/v1/team-builders/xxx. With xxx is deck Id

**Comment by Sizzzles** [comment]
Do they have documentation for api? since I need more than just the team builder to make it work

**Comment by huy4vn** [comment]
No they not public their API, I just try to get from inspect . I read the code, you need to get the comps name too right ? I think when we first loading the https://lolchess.gg/meta we will also saving the comps name and their ids, then we will using this API to get the champ and items

**Comment by Sizzzles** [comment]
Yeah didn't think it was public but thank you so much I've been looking for their API but failed to find it. Honestly if you find anymore that may be useful please let me know

**Comment by huy4vn** [comment]
Yeah, i bad to use load their web and parsing, API is better ^^

**Comment by Sizzzles** [comment]
Little update. I currently have it working with the team builders API you linked. Haven't had a chance to test it completely but comps are loading just need to run through a tft to make sure it all works correctly since I changed a bit and new requirements are needed but that will all be included when I push the changes

**Comment by huy4vn** [comment]
Cool ^^.

**Comment by huy4vn** [comment]
anything news ?

**Comment by Sizzzles** [comment]
Still testing. It works but had an issues with where it was placing units which I'm testing now. If it works I'll push it all before I sleep

**Comment by Sizzzles** [comment]
Pushed update. If you run into any problems let me know
You will need to run pip install -r requirements.txt in Command Prompt again since there are new requirements
If you run into trouble follow install instructions from https://github.com/jfd02/TFT-OCR-BOT

**Comment by Sizzzles** [comment]
Marking as resolved. But will keep open for a few days in case issues arise
