### ISSUE TITLE
Not detecting some units / not placing items

### ISSUE THREAD

**Issue by hadduk** [Sizzzles/TFT-OCR-BOT#7]
Some units like Pyke and Lucian aren't being detected in the shop, also it's not placing items in most units

**Comment by Sizzzles** [comment]
Make sure you delete the cached_data folder so it can get the latest units and comps. I haven't had this issue so this is the only thing I can think of that is causing the issue for you

**Comment by hadduk** [comment]
> 

Thanks! It works perfectly now
