### ISSUE TITLE
Doesn't close game correctly

### ISSUE THREAD

**Issue by Lucas-Di-Prinzio** [Sizzzles/TFT-OCR-BOT#8]
Sometimes when you lose early (8th place) the game wont get closed but the bot start searching for a new match which basically makes you play a match where the bot is not playing. I think this have something to do with the fact that now the surrender button is not available or something

**Comment by Sizzzles** [comment]
Fairly sure it has nothing to do with the surrender button but added sleep before it tries clicking the exit button. Hopefully this fixes it. Let me know if it's still an issue

**Comment by Sizzzles** [comment]
Okay I've delayed the auto queue by 5 seconds. This should fix the problem since it was completely random not just 8th place. The delay should give time for the client to load after games and hopefully stops this issue

**Comment by Sizzzles** [comment]
Changed the queue delay to 10 seconds. I've had success with this. If problem still happens let me know otherwise I'll close this issue in the next few days
