### ISSUE TITLE
help me how to fix it pls

### ISSUE THREAD

**Issue by shuxtyn** [Sizzzles/TFT-OCR-BOT#9]
![image](https://user-images.githubusercontent.com/16521553/228414226-02253b3e-9f16-438b-a7ab-9393e05ac320.png)

**Comment by Sizzzles** [comment]
Want to explain what you are doing for this to happen? Can't really help if you aren't explaining what steps you did to get the error.
But for now I will suggest making sure you have the latest code so download everything again and replacing the already existing files then trying to run main.py again

**Comment by Sizzzles** [comment]
No response. Can reopen if needed.
